"""Add user indices

Revision ID: 07feecaa211b
Revises: eabc5de2ac44
Create Date: 2025-01-02 18:27:17.608766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07feecaa211b'
down_revision = 'eabc5de2ac44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index('idx_user_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=True)
        batch_op.create_index('idx_user_username', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_created_at')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
