"""Rimosso campo accent_color da User

Revision ID: 1d6332d04f33
Revises: f4ffdbf0a50d
Create Date: 2025-01-02 19:35:06.037422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6332d04f33'
down_revision = 'f4ffdbf0a50d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accent_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accent_color', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
