"""Aggiunti campi last_login e login_count a User

Revision ID: a384cd46ac4a
Revises: 07feecaa211b
Create Date: 2025-01-02 19:20:08.884942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a384cd46ac4a'
down_revision = '07feecaa211b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_count')

    # ### end Alembic commands ###
