"""Aggiunti campi theme_preference e accent_color a User

Revision ID: f4ffdbf0a50d
Revises: a384cd46ac4a
Create Date: 2025-01-02 19:27:43.680479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4ffdbf0a50d'
down_revision = 'a384cd46ac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accent_color')
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
